image: microsoft/dotnet:latest

stages:
  - build
  - test
  - publish
  - deploy

build:
  stage: build
  script:
    - 'dotnet restore -s http://robv005:33333/v3/index.json -s https://api.nuget.org/v3/index.json'
    - 'dotnet build'
  tags:
    - docker-executor

test:
  stage: test
  script:
    - 'dotnet restore -s http://robv005:33333/v3/index.json -s https://api.nuget.org/v3/index.json'
    - "dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=\"$PWD/coverage/\" /p:Exclude=\"[xunit*]\" /p:ExcludeByAttribute=\"GeneratedCodeAttribute%2CObsolete%2CCompilerGeneratedAttribute%2CExcludeFromCodeCoverageAttribute\""
    - 'dotnet $(find ~/.nuget/packages/reportgenerator -name ReportGenerator.dll | head -n1) -reports:coverage/coverage.opencover.xml -targetdir:coverage/report -verbosity:Warning -reporttypes:Html'
  coverage: '/Total\s+\|\s+(\d{0,2}\.\d{1,2}%)/'
  artifacts:
    paths:
      - 'coverage'
  tags:
    - docker-executor

# This task is only executed for version tags
nuget-pack-simpleruleengine-lib:
  stage: publish
  only:
    - /^v.*$/
  script:
    - 'cd EssentialRules'
    - 'dotnet restore -s http://robv005:33333/v3/index.json -s https://api.nuget.org/v3/index.json'
    - 'export TAGGED_VERSION=$(echo $CI_COMMIT_REF_NAME | grep -o "\([0-9]*\.\)*[0-9]*")'
    - 'echo $TAGGED_VERSION'
    - dotnet pack -c Release -o ../nuget/
  artifacts:
    paths:
      - 'nuget'
      - 'EssentialRules/bin/Release/'
  tags:
    - docker-executor

# Deploy to JR BaGet server
# This is only done for version tags
baget:
  stage: deploy
  only:
    - /^v.*$/
  except:
    - web
    - schedules
  dependencies:
    - nuget-pack-simpleruleengine-lib
  variables:
    GIT_STRATEGY: none
  environment:
    name: JR BaGet
    url: http://robv005:33333/
  script:
    - 'cd nuget'
    - 'dotnet nuget push *.nupkg -s $JR_BAGET_URL -k $JR_BAGET_API_KEY'
  tags:
    - docker-executor